## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [3]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [90]:
from sklearn.model_selection import train_test_split
X_1 = X[:40]
y_1 = y[:40]
X_2 = X[40:]
y_2 = y[40:]
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1, y_1, test_size=10)
X_2_train, X_2_test, y_2_train, y_2_test = train_test_split(X_2, y_2, test_size=10)

In [91]:
X_test = np.concatenate((X_1_test, X_2_test), axis=0)
y_test = np.concatenate((y_1_test, y_2_test), axis=0)

In [92]:
# concate then shuffle
y_test = y_test.reshape(-1,1)
X_y_test = np.concatenate((X_test, y_test), axis=1)
np.random.shuffle(X_y_test)
X_y_test

array([[100., 101., 102., 103., 104.,   1.],
       [ 25.,  26.,  27.,  28.,  29.,   1.],
       [690., 691., 692., 693., 694.,   0.],
       [ 70.,  71.,  72.,  73.,  74.,   1.],
       [360., 361., 362., 363., 364.,   0.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [800., 801., 802., 803., 804.,   0.],
       [ 45.,  46.,  47.,  48.,  49.,   1.],
       [ 30.,  31.,  32.,  33.,  34.,   1.],
       [600., 601., 602., 603., 604.,   0.],
       [665., 666., 667., 668., 669.,   0.],
       [ 40.,  41.,  42.,  43.,  44.,   1.],
       [500., 501., 502., 503., 504.,   0.],
       [ 90.,  91.,  92.,  93.,  94.,   1.],
       [160., 161., 162., 163., 164.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.],
       [475., 476., 477., 478., 479.,   0.],
       [760., 761., 762., 763., 764.,   0.],
       [815., 816., 817., 818., 819.,   0.],
       [400., 401., 402., 403., 404.,   0.]])

In [96]:
X_y_test_split = np.split(X_y_test,[5,6], axis=1)
X_test = X_y_test_split[0]
y_test = X_y_test_split[1].reshape(1,-1).flatten()

In [97]:
X_test

array([[100., 101., 102., 103., 104.],
       [ 25.,  26.,  27.,  28.,  29.],
       [690., 691., 692., 693., 694.],
       [ 70.,  71.,  72.,  73.,  74.],
       [360., 361., 362., 363., 364.],
       [  0.,   1.,   2.,   3.,   4.],
       [800., 801., 802., 803., 804.],
       [ 45.,  46.,  47.,  48.,  49.],
       [ 30.,  31.,  32.,  33.,  34.],
       [600., 601., 602., 603., 604.],
       [665., 666., 667., 668., 669.],
       [ 40.,  41.,  42.,  43.,  44.],
       [500., 501., 502., 503., 504.],
       [ 90.,  91.,  92.,  93.,  94.],
       [160., 161., 162., 163., 164.],
       [ 20.,  21.,  22.,  23.,  24.],
       [475., 476., 477., 478., 479.],
       [760., 761., 762., 763., 764.],
       [815., 816., 817., 818., 819.],
       [400., 401., 402., 403., 404.]])

In [98]:
y_test

array([1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 0., 0.])